### ISSUE TITLE
Path to next atomate2 release

### ISSUE THREAD

**Issue by utf** [materialsproject/atomate2#721]
Currently we are stuck in dependency hell which is preventing a new release of atomate2. I've setup this issue to track the various PR's and dependency releases needed to get a new version out.

- [x] **emmet**: materialsproject/emmet#937
- [x] **emmet**: New emmet version released
- [x] **pymatgen**: New pymatgen version released containing https://github.com/materialsproject/pymatgen/pull/3617
- [x] **atomate2**: #720
- [x] **atomate2**: #739 
- [x] **atomate2**: Update pymatgen 
- [x] **atomate2**: Fix import of MP workflows #708 

These are the essential fixes. If there are any other PRs people would like to prioritise for the next release then please let me know. Currently, I'm also tracking the following PRs which are less critical/should be mergeable once the above are completed:

- [x] **custodian**: New release needed containing materialsproject/custodian#298
- [x] **emmet**: materialsproject/emmet#925
- [x] **atomate2**: #655
- [x] **atomate2**: #623
- [x] **atomate2**: #562
- [x] **atomate2**: #600

 In the meantime, it is recommended to install atomate2 with the strict dependency selection, which is guaranteed to give a working installation.
 ```
pip install atomate2[strict]
```

**Comment by utf** [comment]
@janosh would you be ok to release a new pymatgen version?

**Comment by janosh** [comment]
@utf sure, i'll [take a look at custodian first](https://github.com/materialsproject/atomate2/pull/600#issuecomment-1945722778) though. i forgot why the release failed but it was on my todo list

**Comment by utf** [comment]
Thanks you! It's much appreciated.

**Comment by janosh** [comment]
so it looks like the release failed because the `test.yml` and `release.yml` workflows use different setups. the latter install `openbabel` through `miniconda`, the former doesn't. as a result only a subset of tests are running on PRs but the full test suite when trying to make release. not sure when it became this way

**Comment by janosh** [comment]
[custodian==v2024.2.15](https://github.com/materialsproject/custodian/releases/tag/v2024.2.15) is [now on PyPI](https://pypi.org/project/custodian/2024.2.15).

**Comment by utf** [comment]
Fantastic, thanks @janosh.

**Comment by mkhorton** [comment]
> would you be ok to release a new pymatgen version?

This has now been done too.

**Comment by utf** [comment]
Brilliant thank you. We're just waiting on a new emmet release.
